=== alejandrafau/pydatajson/pydatajson/schemas/catalog.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"required": [
		"dataset",
		"title",
		"description",
		"publisher",
		"superThemeTaxonomy"
	],
	"properties": {
		"publisher": {
			"type": "object",
			"required": ["name", "mbox"],
			"properties": {
				"name": { "$ref": "mixed-types.json#nonEmptyString" },
				"mbox": { 
					"type": "string",
			       		"format": "email"
				}
			}
		},
		"dataset": {
			"type": "array",
			"items": { "$ref": "dataset.json" }
		},
		"title": { "$ref": "mixed-types.json#nonEmptyString" },
		"description": { "$ref": "mixed-types.json#nonEmptyString" },
		"superThemeTaxonomy": { "$ref": "mixed-types.json#nonEmptyString" },
		"issued": { "$ref": "mixed-types.json#nonEmptyStringOrNull" },
		"modified": { "$ref": "mixed-types.json#nonEmptyStringOrNull" },
		"language": { "$ref": "mixed-types.json#arrayOrNull" },
		"themeTaxonomy": {
			"anyOf": [
				{ 
					"type": "array",
					"items": { "$ref": "theme.json" }
				},
				{ "type": "null" }
			]
	       	},
		"license": { "$ref": "mixed-types.json#nonEmptyStringOrNull" },
		"homepage": { "$ref": "mixed-types.json#nonEmptyStringOrNull" },
		"rights": { "$ref": "mixed-types.json#nonEmptyStringOrNull" },
		"spatial": {
			"anyOf": [
				{ "type": "string" },
				{ "type": "array" },
				{ "type": "null" }
			]
		}
	}
}

=== alejandrafau/pydatajson/pydatajson/catalog_fields.json
{
    "title": "requerido",
    "description": "requerido",
    "publisher": {
      "name": "requerido",
      "mbox": "requerido"
    },
    "issued": "recomendado",
    "modified": "recomendado",
    "language": "recomendado",
    "superThemeTaxonomy": "requerido",
    "themeTaxonomy": "recomendado",
    "license": "recomendado",
    "homepage": "recomendado",
    "rights": "opcional",
    "spatial": "opcional",
    "dataset": [
        {
            "title": "requerido",
            "description": "requerido",
            "publisher": {
              "name": "requerido",
              "mbox": "recomendado"
            },
            "contactPoint": {
              "fn": "recomendado",
              "hasEmail": "recomendado"
            },
            "superTheme": "requerido",
            "theme": "recomendado",
            "keyword": "recomendado",
            "accrualPeriodicity": "requerido",
            "issued": "requerido",
            "modified": "recomendado",
            "identifier": "opcional",
            "language": "opcional",
            "spatial": "opcional",
            "temporal": "recomendado",
            "landingPage": "opcional",
            "license": "recomendado",
            "distribution": [
                {
                    "accessURL": "requerido",
                    "description": "recomendado",
                    "format": "recomendado",
                    "mediaType": "opcional",
                    "downloadURL": "requerido",
                    "title": "requerido",
                    "license": "recomendado",
                    "byteSize": "opcional",
                    "issued": "requerido",
                    "modified": "recomendado",
                    "rights": "opcional",
                    "field": "recomendado"
                }
            ]
        }
    ]
}
